questions =  [
    {"id": 0, "question": "La libertà d'impresa è il miglior modo per far prosperare la società.", "effects": {"right": 1}},
    {"id": 1, "question": "La carità è meglio della sicurezza sociale nell'aiutare le persone in difficoltà.", "effects": {"right": 1}},
    {"id": 2, "question": "Gli stipendi sono sempre giusti perchè un datore di lavoro sa quanto vale il lavoro svolto da un suo dipendente.", "effects": {"right": 1}},
    {"id": 3, "question": "L'avarizia è parte della natura umana.", "effects": {"right": 1}},
    {"id": 4, "question": "Lo \"sfruttamento\" è un concetto datato perché i problemi del capitalismo del 1800 non esistono più.", "effects": {"right": 1}},
    {"id": 5, "question": "Il comunismo è un ideale che non potrà mai essere messo in pratica.", "effects": {"right": 1}},
    {"id": 6, "question": "La tassazione dei ricchi non è una buona idea, la società sarebbe migliore senza di essa.", "effects": {"right": 1}},
    {"id": 7, "question": "Più si lavora duro, più si sale la \"scala sociale\".", "effects": {"right": 1}},
    {"id": 8, "question": "Le società e le corporazione non sono affidabili, perciò dovrebbero essere regolamentate dal governo.", "effects": {"right": -1}},
    {"id": 9, "question": "Un governo che provvede per tutti è essenzialmente una buona idea.", "effects": {"right": -1}},
    {"id": 10, "question": "L'attuale sistema di welfare dovrebbe essere potenziato per combattere le disuguaglianze.", "effects": {"right": -1}},
    {"id": 11, "question": "Gli appezzamenti di terreno non dovrebbero essere un bene da vendere e comprare.", "effects": {"right": -1}},
    {"id": 12, "question": "Tutte le industrie e le banche dovrebbero essere statalizzate.", "effects": {"right": -1}},
    {"id": 13, "question": "La classe sociale è la principale forma di divisione della società.", "effects": {"right": -1}},
    {"id": 14, "question": "Le disuguaglianze economiche sono troppo grandi nel mondo.", "effects": {"right": -1}},
    {"id": 15, "question": "È giusto che il governo spii i cittadini per combattere gli estremismi e il terrorismo.", "effects": {"auth": 1}},
    {"id": 16, "question": "Una figura politica autoritaria, se moralmente corretta, è una buona cosa per la società.", "effects": {"auth": 1}},
    {"id": 17, "question": "Un governo, per avere successo, deve essere tenace.", "effects": {"auth": 1}},
    {"id": 18, "question": "Solo il governo ha la capacità di regolare effettivamente ed in modo giusto le società.", "effects": {"auth": 1}},
    {"id": 19, "question": "La società richiede una burocrazia e una gerarchia per funzionare.", "effects": {"auth": 1}},
    {"id": 20, "question": "Le carte d'identità dovrebbero essere obbligatorie per mantenere la sicurezza pubblica.", "effects": {"auth": 1}},
    {"id": 21, "question": "In tempi di crisi la sicurezza diventa più importante delle libertà civili.", "effects": {"auth": 1}},
    {"id": 22, "question": "Se non hai niente da nascondere, non hai motivo di avere paura.", "effects": {"auth": 1}},
    {"id": 23, "question": "Il governo dovrebbe essere meno coinvolto nella vita dei propri cittadini.", "effects": {"auth": -1}},
    {"id": 24, "question": "Senza la democrazia la società non ha un valore.", "effects": {"auth": -1}},
    {"id": 25, "question": "L'annullamento della giuria \"Jury nullification\" dovrebbe essere legale.", "effects": {"auth": -1}},
    {"id": 26, "question": "Un governo minimo rende le persone più libere.", "effects": {"auth": -1}},
    {"id": 27, "question": "Il governo dovrebbe fornire solo servizi di emergenza e di polizia.", "effects": {"auth": -1}},
    {"id": 28, "question": "La polizia è stata create per mantenere lo status quo con la forza, non per proteggere le persone.", "effects": {"auth": -1}},
    {"id": 29, "question": "Le scuole statali sono una brutta idea perché lo stato non dovrebbe influenzare i nostri figli.", "effects": {"auth": -1}},
    {"id": 30, "question": "Due individue consenziente dovrebbere poter fare ciò che vogliono, anche se ciò che fanno mi mette a disagio.", "effects": {"prog": 1}},
    {"id": 31, "question": "Il corpo di una persona è di sua proprietà e ogni persona dovrebbe poter fare ciò che vuole con il suo corpo.", "effects": {"prog": 1}},
    {"id": 32, "question": "Una persona dovrebbe essere libera di credere in ciò che vuole.", "effects": {"prog": 1}},
    {"id": 33, "question": "La nudità è naturale.", "effects": {"prog": 1}},
    {"id": 34, "question": "Gli animali dovrebbero avere dei diritti universali.", "effects": {"prog": 1}},
    {"id": 35, "question": "Il genere di una persona è un costrutto sociale, non uno stato di fatto.", "effects": {"prog": 1}},
    {"id": 36, "question": "Leggi basate su valori culturali, piuttosto che su valori etici, sono ingiuste.", "effects": {"prog": 1}},
    {"id": 37, "question": "La libertà di agire sul proprio corpo dovrebbe essere data anche ai minorenni, alle persone con problemi mentali e ai criminali.", "effects": {"prog": 1}},
    {"id": 38, "question": "L'omosessualità è contro i miei valori.", "effects": {"prog": -1}},
    {"id": 39, "question": "Gli individui transgender non dovrebbero avere la possibilità di adottare dei bambini.", "effects": {"prog": -1}},
    {"id": 40, "question": "Le droghe sono dannose e quindi dovrebbero essere illegali.", "effects": {"prog": -1}},
    {"id": 41, "question": "La pena di morte dovrebbe essere un'opzione per alcuni crimini.", "effects": {"prog": -1}},
    {"id": 42, "question": "I crimini senza vittime dovrebbero comunque essere puniti.", "effects": {"prog": -1}},
    {"id": 43, "question": "Una persona non può avere una morale senza essere religioso.", "effects": {"prog": -1}},
    {"id": 44, "question": "I genitori dovrebbero avere potere assoluto sui loro figli, perché i genitori sono più grandi e con più esperienza rispetto ai figli.", "effects": {"prog": -1}},
    {"id": 45, "question": "Il multiculturalismo è sbagliato.", "effects": {"prog": -1}}
];
